---
- name: Add weechat repository gpg-key
  become: true
  apt_key:
    keyserver: 'keys.openpgp.org'
    id: "{{ weechat.gpg_id }}"
    state: present

- name: add weechat repo
  become: true
  apt_repository:
    repo: "deb https://weechat.org/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: add weechat repo-src
  become: true
  apt_repository:
    repo: "deb-src https://weechat.org/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes


- name: install recomended weechat packages
  become: true
  apt:
    name:
     - weechat-curses
     - weechat-plugins
     - weechat-python
     - weechat-perl
     - weechat-lua
     - weechaz-ruby
     - weechat-doc
    state: present
