---
- name: install weechat if available
  package:
    name:
      - weechat
      - weechat-plugins
      - weechat-python
      - weechat-perl
      - weechat-lua
      - weechaz-ruby
      - weechat-doc
    state: present
