---
- name: install apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: present

- name: Add weechat repository gpg-key
  become: true
  apt_key:
    keyserver: 'keys.openpgp.org'
    id: "{{ weechat.gpg_id }}"
    state: present

- name: add weechat repo
  become: true
  apt_repository:
    repo: "deb {{ weechat__debian_weechat_repo }}"
    state: present
    update_cache: true

- name: add weechat repo-src
  become: true
  apt_repository:
    repo: "deb-src {{ weechat__debian_weechat_repo }}"
    state: present
    update_cache: true

- name: install recomended weechat packages
  become: true
  apt:
    name:
      - weechat-curses
      - weechat-plugins
      - weechat-python
      - weechat-perl
      - weechat-lua
      - weechat-ruby
      - weechat-doc
    state: present
