---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: "install-{{ ansible_os_family|lower }}.yml"
  when: install_weechat | bool

- include_tasks: directorys.yml
  when: configure_weechat | bool
