---
- name: install tmux to launch weechat
  become: true
  ansible.builtin.package:
    name: tmux
    state: present
  when: weechat.install | bool

- name: copy systemd service for weechat
  become: true
  ansible.builtin.template:
    src: templates/weechat.service
    dest: /etc/systemd/system/weechat.service
    owner: root
    group: root
    mode: '0644'
  notify: systemctl restart weechat.service

- name: enable weechat.service
  become: true
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: weechat.service
    daemon_reload: true
  notify: systemctl restart weechat.service
